experiment:
  paradigm: 2 #0 - same start&goal per reset, 1 - random start same goal per reset, 2 - random start and goal per reset
  goal:
    mode: random_per_run
    radius: 0.3

robots:
  - name: robot1
    deploy: true
    spawn: [0.0, 0.0, 0.0] # robot position (x,y,yaw)
    maze_spawn: [0.0, 0.0, 0.0] # maze position (x,y,yaw)
    loggers: [odom, lidar, velocity]

  # - name: robot2
  #   deploy: true
  #   spawn: [7.0, 0.0, 0.0]
  #   maze_spawn: [7.0, 0.0, 0.0] # offset by 7 units â†’ no wall overlap
  #   loggers: [odom, lidar, velocity]

  # - name: robot3
  #   deploy: true
  #   spawn: [0.0, 7.0, 0.0]
  #   maze_spawn: [0.0, 7.0, 0.0]
  #   loggers: [odom, lidar, velocity]
